import { Link } from 'react-router-dom';
import { motion, Variants } from 'framer-motion';
import SeoHead from '@/components/SeoHead';
import Footer from '@/components/Footer';
import { useDemoBooking } from '@/contexts/DemoBookingContext';
import { webPageSchema } from '@/lib/seo/schemas';
import { Vortex } from '@/components/ui/vortex';
import styles from './ProductPage.module.css';

const easeOutExpo = [0.16, 0.84, 0.44, 1] as const;
const easeOutQuart = [0.25, 0.46, 0.45, 0.94] as const;

const container: Variants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: { staggerChildren: 0.1, delayChildren: 0.15 },
  },
};

const item: Variants = {
  hidden: { opacity: 0, y: 24, scale: 0.98 },
  visible: {
    opacity: 1,
    y: 0,
    scale: 1,
    transition: { duration: 0.8, ease: easeOutQuart },
  },
};

const titleLine: Variants = {
  hidden: { opacity: 0, y: 20, filter: 'blur(6px)' },
  visible: {
    opacity: 1,
    y: 0,
    filter: 'blur(0px)',
    transition: { duration: 0.9, ease: easeOutExpo },
  },
};

const ProductPage = () => {
  const { openDemoBooking } = useDemoBooking();

  return (
    <>
      {/* Black-dominant atmosphere with violet energy generated by the vortex */}
      <div className={styles.productPageBg}>
        <Vortex
          particleCount={150}
          baseHue={266}
          rangeSpeed={0.34}
          baseRadius={1.0}
          rangeRadius={1.7}
          backgroundColor="#04050a"
          containerClassName="w-full h-full"
        />
        <div className={styles.productPageAtmosphere} />
      </div>

      {/* Content over background */}
      <main className="relative z-20 min-h-screen pt-14 md:pt-16">
        <div className={styles.productPage}>
          <div className={styles.productPageContent}>
        <SeoHead
          title="Product | Elystra — The Rail From Scope to Collected Payment"
          description="Elystra is the commercial rail agencies run deals through: priced scope, signature, deposit, and downstream operations in one controlled sequence."
          path="/product"
          jsonLd={[
            webPageSchema(
              '/product',
              'Product | Elystra',
              'The commercial rail agencies run deals through: priced scope, signature, deposit, and downstream operations in one controlled sequence.',
            ),
          ]}
        />

        <section className={styles.hero}>
          <motion.div
            className={styles.wrap}
            variants={container}
            initial="hidden"
            animate="visible"
          >
            <motion.div variants={item} className={styles.state}>The commercial rail</motion.div>
            <motion.h1 variants={titleLine}>
              Between the yes and the money, agencies run on <em>nothing</em>.
            </motion.h1>
            <motion.p variants={item} className={styles.lede}>
              Every agency has a system for winning work and a system for delivering it. Almost none have a system for the window in between — where scope is still verbal, commitment is still loose, and revenue is still theoretical. <strong>Elystra is that system.</strong>
            </motion.p>
          </motion.div>
        </section>

        <section className={styles.gapBand}>
          <motion.div
            className={styles.wrap}
            variants={container}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, amount: 0.3 }}
          >
            <motion.div variants={item} className={styles.state}>Where revenue leaks</motion.div>
            <motion.h2 variants={titleLine}>The deal is won on the call. It is lost in the days after.</motion.h2>
            <motion.p variants={item}>A prospect says yes on Tuesday. The proposal goes out Friday. It sits unopened until the following Wednesday. Someone forwards it to a partner who was never in the conversation. Follow-up happens on a hunch. The deposit clears — if it clears — two weeks after the moment the client was most ready to pay. Nothing in that sequence is measured, so nothing in it improves.</motion.p>

            <motion.div
              className={styles.leaks}
              variants={{
                hidden: { opacity: 0 },
                visible: {
                  opacity: 1,
                  transition: { staggerChildren: 0.08, delayChildren: 0.1 },
                },
              }}
            >
              <motion.div variants={item} className={styles.leak}>
                <div className={styles.n}>01</div>
                <h3>Scope drift</h3>
                <p>Time between the conversation and the priced document is time for the client to shrink the deal in their head.</p>
              </motion.div>
              <motion.div variants={item} className={styles.leak}>
                <div className={styles.n}>02</div>
                <h3>Signature friction</h3>
                <p>Sign here, then pay over there. Two tools, two moments, two chances to stall.</p>
              </motion.div>
              <motion.div variants={item} className={styles.leak}>
                <div className={styles.n}>03</div>
                <h3>Blind follow-up</h3>
                <p>No visibility into who opened what, who forwarded it, or which deal is actually still alive.</p>
              </motion.div>
              <motion.div variants={item} className={styles.leak}>
                <div className={styles.n}>04</div>
                <h3>Handoff decay</h3>
                <p>Closed–won lives in one person's inbox. Finance, delivery, and onboarding find out late.</p>
              </motion.div>
            </motion.div>
          </motion.div>
        </section>

        <section className={styles.rail}>
          <div className={styles.wrap}>
            <div className={styles.railIntro}>
              <div className={styles.state}>The sequence</div>
              <h2>One rail. Four states. No dead time between them.</h2>
              <p>Elystra is not a set of tools an agency assembles. It is a single controlled sequence a deal travels through, where each state transition is triggered by a real event — not by someone remembering to do the next thing.</p>
            </div>

            <div className={styles.stage}>
              <div className={styles.stageHead}>
                <span className={styles.stageNum}>STATE 01</span>
                <span className={styles.stageLabel}>Scope</span>
              </div>
              <h3>The conversation becomes a priced document.</h3>
              <p className={styles.sub}>Upload the call notes, the transcript, or the recording. Elystra reads it against your agency's own package structure and pricing logic, and returns a send-ready scope in your brand — not a template you then spend an afternoon correcting.</p>
              <ul>
                <li><span className={styles.k}>Input</span><span className={styles.v}>Notes, transcripts, or call recordings — whatever the conversation actually produced</span></li>
                <li><span className={styles.k}>Mapping</span><span className={styles.v}>Your existing service packages, tiers, and pricing rules. <strong>Not a generic proposal template.</strong></span></li>
                <li><span className={styles.k}>Brand</span><span className={styles.v}>Typefaces, colors, and layout locked to your agency's identity across every send</span></li>
                <li><span className={styles.k}>Output</span><span className={styles.v}>A live, trackable scope — sendable while the client is still warm</span></li>
              </ul>
              <div className={styles.transition}>SCOPE SENT <span>→ triggers</span> LIVE TRACKING</div>
            </div>

            <div className={styles.stage}>
              <div className={styles.stageHead}>
                <span className={styles.stageNum}>STATE 02</span>
                <span className={styles.stageLabel}>Commit</span>
              </div>
              <h3>Agreement and payment collapse into one motion.</h3>
              <p className={styles.sub}>The client reviews the scope, signs, and pays the deposit or first retainer on the same screen, in the same session. There is no second tab, no separate payment link sent the next morning, no gap between the moment of intent and the moment of transfer.</p>
              <ul>
                <li><span className={styles.k}>Review</span><span className={styles.v}>A live document, not a static PDF attachment — every interaction is instrumented</span></li>
                <li><span className={styles.k}>Signature</span><span className={styles.v}>Captured in-rail. No third-party signing tool in the path.</span></li>
                <li><span className={styles.k}>Payment</span><span className={styles.v}>Deposit or retainer collected in the same flow as the signature</span></li>
                <li><span className={styles.k}>State</span><span className={styles.v}><strong>Cleared funds move the deal to Closed–Won.</strong> Not a signature. Not a verbal. Money.</span></li>
              </ul>
              <div className={styles.transition}>PAYMENT CLEARED <span>→ triggers</span> DOWNSTREAM EXECUTION</div>
            </div>

            <div className={styles.stage}>
              <div className={styles.stageHead}>
                <span className={styles.stageNum}>STATE 03</span>
                <span className={styles.stageLabel}>Pressure</span>
              </div>
              <h3>Follow-up stops being a guess.</h3>
              <p className={styles.sub}>Every live scope reports back. Opens, time spent on the pricing section, re-opens, forwards to people who were never on the call, silence after a specific page. Elystra converts that behavior into a heat score per deal and a ranked queue of who is worth touching today — and what to say when you do.</p>
              <ul>
                <li><span className={styles.k}>Signals</span><span className={styles.v}>Open events, dwell time by section, re-opens, forward patterns, new stakeholders surfacing</span></li>
                <li><span className={styles.k}>Scoring</span><span className={styles.v}>Each deal carries a live temperature: hot, watching pricing, cooling, dormant</span></li>
                <li><span className={styles.k}>Queue</span><span className={styles.v}>A ranked list of deals worth a touch today, ordered by movement — not by age</span></li>
                <li><span className={styles.k}>Direction</span><span className={styles.v}>Suggested next move derived from what the buyer actually did, not a cadence template</span></li>
              </ul>
              <div className={styles.transition}>BEHAVIOR OBSERVED <span>→ compounds into</span> OFFER INTELLIGENCE</div>
            </div>

            <div className={styles.stage}>
              <div className={styles.stageHead}>
                <span className={styles.stageNum}>STATE 04</span>
                <span className={styles.stageLabel}>Operate</span>
              </div>
              <h3>The close fires the whole stack, then holds the client.</h3>
              <p className={styles.sub}>The moment payment clears, Elystra pushes the record into your CRM, opens delivery tasks in your project system, notifies finance, and starts onboarding. The client gets a portal that holds every agreement, invoice, and receipt — and becomes the channel through which the next scope is requested.</p>
              <ul>
                <li><span className={styles.k}>CRM</span><span className={styles.v}>Record created and stage-advanced automatically on cleared payment</span></li>
                <li><span className={styles.k}>Delivery</span><span className={styles.v}>Project tasks opened against the signed scope — not re-typed from it</span></li>
                <li><span className={styles.k}>Finance</span><span className={styles.v}>Invoicing and revenue records written at the transaction, not reconciled after</span></li>
                <li><span className={styles.k}>Portal</span><span className={styles.v}>Agreements, invoices, receipts, renewals — and <strong>expansion requests initiated by the client</strong></span></li>
              </ul>
              <div className={styles.transition}>CLIENT ACTIVE <span>→ portal behavior surfaces</span> EXPANSION SIGNAL</div>
            </div>
          </div>
        </section>

        <section className={styles.switch}>
          <div className={styles.wrap}>
            <div className={styles.state}>Adoption</div>
            <h2>The rail fits the stack. It does not replace it.</h2>
            <p>The reason agencies stay on a broken process is rarely that they like it. It is that switching looks expensive and nobody wants to own the migration. Elystra is built to sit on top of what you already run — your CRM, your project system, your billing — and to be operational before anyone has to change a habit.</p>
            <div className={styles.switchGrid}>
              <div className={styles.sw}>
                <h3>Keep your systems</h3>
                <p>Elystra connects to the CRM, docs, billing, project management, and automation tools you already pay for. The rail routes into them. It does not ask you to abandon them.</p>
              </div>
              <div className={styles.sw}>
                <h3>No migration project</h3>
                <p>There is no historical data import to schedule, no records to re-key, no freeze window. The rail starts with your next deal, not your last hundred.</p>
              </div>
              <div className={styles.sw}>
                <h3>Deals in flight stay in flight</h3>
                <p>Live opportunities continue on whatever path they're on. Elystra takes the next scope you build, and the one after that.</p>
              </div>
              <div className={styles.sw}>
                <h3>Baseline captured on day one</h3>
                <p>Before anything changes, Elystra records how your revenue currently moves. Every improvement afterward is measured against your own numbers, not an industry claim.</p>
              </div>
            </div>
          </div>
        </section>

        <section className={styles.close}>
          <div className={styles.wrap}>
            <div className={styles.state}>Next</div>
            <h2>Serious agencies do not need more software. They need control over how money moves.</h2>
            <p>See the rail run against one of your own deals — a real scope, a real signature flow, a real payment event — in under thirty minutes.</p>
            <button type="button" className={styles.cta} onClick={() => openDemoBooking()}>
              Request a walkthrough
            </button>
            <div className={styles.subLinks}>
              <Link to="/integrations">Integrations</Link> &nbsp;·&nbsp; <Link to="/docs">Documentation</Link> &nbsp;·&nbsp; <Link to="/security">Security</Link>
            </div>
          </div>
        </section>
        </div>
        </div>
        </main>
    <Footer />
    </>
  );
};

export default ProductPage;
